[application]

# App (Project) Name
name = "notabene"

[bundle]
identifier = "com.jaeger.notabene"
publisher = "Jaeger"
icon = ["assets/icon.png"]

[web.app]

# HTML title tag content
title = "notabene"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
